lastupdatecheck: 0
recentrepos:
- /Users/chris/git/dotfiles
- /Users/chris/go/src/github.com/mattermost/mattermost-mobile
- /Users/chris/go/src/github.com/mattermost/push-proxy
- /Users/chris/go/src/github.com/mattermost/calls
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
diffcontextsize: 3
