lastupdatecheck: 0
recentrepos:
- /home/chris/git/dotfiles
- /Users/chris/go/src/github.com/mattermost/calls
- /Users/chris/git/dotfiles
- /Users/chris/go/src/github.com/mattermost/mattermost-mobile
- /Users/chris/go/src/github.com/mattermost/push-proxy
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
ignorewhitespaceindiffview: false
